@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class)
package com.junchen.jingdu

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Pause
import androidx.compose.material.icons.filled.VolumeUp
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlin.math.roundToInt

@Composable internal fun ProductSettingsSheet(state: AppUiState, actions: JingduActions) {
    val settings = state.settings
    ModalBottomSheet(onDismissRequest = actions.onClosePanel) {
        LazyColumn(modifier = Modifier.fillMaxWidth().fillMaxHeight(0.9f), contentPadding = PaddingValues(start = 20.dp, end = 20.dp, bottom = 36.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
            item { Column(Modifier.fillMaxWidth()) { Text(stringResource(R.string.reading_settings), style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.SemiBold); Spacer(Modifier.height(4.dp)); Text(stringResource(R.string.settings_subtitle), style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant) } }
            item { SettingSection(stringResource(R.string.page_tone)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { ReaderPalette.entries.forEach { p -> FilterChip(settings.palette == p, { actions.onSettingsChanged(settings.copy(palette = p)) }, label = { Text(stringResource(when (p) { ReaderPalette.PAPER -> R.string.paper; ReaderPalette.LIGHT -> R.string.light; ReaderPalette.NIGHT -> R.string.night })) }) } } } }
            item { SettingSection(stringResource(R.string.font)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { ReaderTypeface.entries.forEach { f -> FilterChip(settings.typeface == f, { actions.onSettingsChanged(settings.copy(typeface = f)) }, label = { Text(stringResource(if (f == ReaderTypeface.SYSTEM) R.string.system_font else R.string.serif)) }) } } } }
            item { ReaderSlider(stringResource(R.string.font_size), settings.fontSizeSp, 16f..34f, "${settings.fontSizeSp.roundToInt()}sp") { actions.onSettingsChanged(settings.copy(fontSizeSp = it)) } }
            item { ReaderSlider(stringResource(R.string.line_spacing), settings.lineHeightMultiplier, 1.2f..2.0f, String.format("%.2f×", settings.lineHeightMultiplier)) { actions.onSettingsChanged(settings.copy(lineHeightMultiplier = it)) } }
            item { ReaderSlider(stringResource(R.string.side_margins), settings.horizontalPaddingDp, 12f..48f, "${settings.horizontalPaddingDp.roundToInt()}dp") { actions.onSettingsChanged(settings.copy(horizontalPaddingDp = it)) } }
            item { HorizontalDivider() }
            item { SettingSection(stringResource(R.string.read_aloud)) { ReaderSlider(stringResource(R.string.speech_rate), settings.ttsRate, 0.6f..1.8f, String.format("%.1f×", settings.ttsRate)) { actions.onSettingsChanged(settings.copy(ttsRate = it)) }; ReaderSlider(stringResource(R.string.speech_pitch), settings.ttsPitch, 0.7f..1.4f, String.format("%.1f×", settings.ttsPitch)) { actions.onSettingsChanged(settings.copy(ttsPitch = it)) }; OutlinedButton(onClick = actions.onToggleTts, modifier = Modifier.fillMaxWidth()) { Icon(if (state.ttsPlaying) Icons.Default.Pause else Icons.Default.VolumeUp, null); Spacer(Modifier.width(8.dp)); Text(stringResource(if (state.ttsPlaying) R.string.pause_read_aloud else R.string.read_from_here)) } } }
            item { ElevatedCard(Modifier.fillMaxWidth()) { Column(Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Icon(Icons.Outlined.RecordVoiceOver, null, tint = MaterialTheme.colorScheme.primary); Text(stringResource(R.string.offline_voice), fontWeight = FontWeight.SemiBold); AssistChip(onClick = {}, label = { Text("Pro") }) }; Text(stringResource(R.string.offline_voice_body), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant); val suffix = state.proPrice?.let { stringResource(R.string.price_suffix, it) } ?: ""; if (!state.proUnlocked) OutlinedButton(onClick = actions.onUpgradePro, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Outlined.Lock, null); Spacer(Modifier.width(8.dp)); Text(stringResource(R.string.unlock_pro_voice, suffix)) } else if (state.ttsVoices.isEmpty()) Text(stringResource(R.string.no_offline_voice), color = MaterialTheme.colorScheme.onSurfaceVariant) else Column(verticalArrangement = Arrangement.spacedBy(6.dp)) { FilterChip(settings.ttsVoiceName.isEmpty(), { actions.onSettingsChanged(settings.copy(ttsVoiceName = "")) }, label = { Text(stringResource(R.string.system_default)) }); state.ttsVoices.take(12).forEach { v -> FilterChip(settings.ttsVoiceName == v.name, { actions.onSettingsChanged(settings.copy(ttsVoiceName = v.name)) }, label = { Text(v.label) }) }; if (state.ttsVoices.size > 12) Text(stringResource(R.string.more_offline_voices, state.ttsVoices.size - 12), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant) } } } }
            item { SettingSection(stringResource(R.string.auto_page)) { ReaderSlider(stringResource(R.string.interval), settings.autoPageDelayMs.toFloat(), 2500f..15000f, stringResource(R.string.seconds_value, settings.autoPageDelayMs / 1000f)) { actions.onSettingsChanged(settings.copy(autoPageDelayMs = it.toLong())) }; OutlinedButton(onClick = actions.onToggleAutoPaging, modifier = Modifier.fillMaxWidth()) { Text(stringResource(if (state.autoPaging) R.string.stop_auto_page else R.string.start_auto_page)) } } }
            item { SettingSection(stringResource(R.string.sleep_timer)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { listOf(0, 15, 30, 60).forEach { m -> FilterChip(state.sleepMinutes == m, { actions.onSleepTimer(m) }, label = { Text(if (m == 0) stringResource(R.string.off) else stringResource(R.string.minutes_value, m)) }) } } } }
            item { HorizontalDivider() }
            item { ElevatedCard(Modifier.fillMaxWidth()) { Column(Modifier.fillMaxWidth().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Icon(Icons.Outlined.CloudOff, null, tint = MaterialTheme.colorScheme.primary); Text(stringResource(R.string.local_asset_backup), fontWeight = FontWeight.SemiBold); AssistChip(onClick = {}, label = { Text("Pro") }) }; Text(stringResource(R.string.local_asset_backup_body), style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant); if (state.proUnlocked) Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedButton(onClick = actions.onExportBackup, modifier = Modifier.weight(1f)) { Icon(Icons.Outlined.FileUpload, null); Spacer(Modifier.width(6.dp)); Text(stringResource(R.string.export_backup)) }; OutlinedButton(onClick = actions.onImportBackup, modifier = Modifier.weight(1f)) { Icon(Icons.Outlined.FileDownload, null); Spacer(Modifier.width(6.dp)); Text(stringResource(R.string.restore_backup)) } } else OutlinedButton(onClick = actions.onUpgradePro, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Outlined.WorkspacePremium, null); Spacer(Modifier.width(8.dp)); Text(stringResource(R.string.unlock_pro_backup)) } } } }
            item { TextButton(onClick = actions.onRestorePro, modifier = Modifier.fillMaxWidth()) { Text(stringResource(if (state.proUnlocked) R.string.pro_unlocked_recheck else R.string.restore_jingdu_pro)) } }
        }
    }
}

@Composable private fun ReaderSlider(label: String, value: Float, range: ClosedFloatingPointRange<Float>, valueText: String, onChange: (Float) -> Unit) { Column { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(label, style = MaterialTheme.typography.bodyMedium); Text(valueText, style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.primary) }; Slider(value = value, onValueChange = onChange, valueRange = range) } }
@Composable private fun SettingSection(title: String, content: @Composable () -> Unit) { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) { Text(title, style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.SemiBold); content() } }
